<?php

class create_imagecopy_config {

  public static $variantNodeTypes =  array (
          'price'
        );

  public static $weight =  3;

  public static   $cities = array (
          array('text' => 'Mumbai', 'value' => 'Mumbai'),
          array('text' => 'Delhi', 'value' => 'Delhi'),
          array('text' => 'Bangalore', 'value' => 'Bangalore'),
          array('text' => 'Kolkatta', 'value' => 'Kolkatta'),
          array('text' => 'Hyderabad', 'value' => 'Hyderabad'),
          array('text' => 'Chennai', 'value' => 'Chennai'),
          array('text' => 'Pune', 'value' => 'Pune'),
          array('text' => 'Cochin', 'value' => 'Cochin'),
          array('text' => 'Others', 'value' => 'Others')
        );

}
