<div class="roundAll3 cta buySellCity">
	<h3 class="padB5">Buy &amp; Sell<br />USED CARS</h3>
		<ul class="price">
			<li><a href="http://classifieds.team-bhp.com/search_results/?action=search&listing_type[equal]=Car&ZipCode[geo][radius]=150&MakeModel[tree][1]=&MakeModel[tree][2]=0&ZipCode[geo][location]=&Price[not_more]=200000&qs_button=Find" title="Rs.2 Lakhs or less"><span class="WebRupee">Rs.</span> 2 Lakhs or less</a></li>
			<li><a href="http://classifieds.team-bhp.com/search_results/?action=search&listing_type%5Bequal%5D=Car&MakeModel%5Btree%5D%5B1%5D=&MakeModel%5Btree%5D%5B2%5D=0&multyModelMode=&Price%5Bnot_less%5D=200000&Price%5Bnot_more%5D=400000&ZipCode%5Bgeo%5D%5Bradius%5D=150&ZipCode%5Bgeo%5D%5Blocation%5D=&CarYear%5Bnot_less%5D=1940&CarYear%5Bnot_more%5D=2011&CarMileage%5Bnot_more%5D=&CarRegistrationState%5Bequal%5D=&CarFuelType%5Bequal%5D=&CarTransmission%5Bequal%5D=&CarExteriorColor%5Bequal%5D=&CarTaxPaid%5Bequal%5D=&user_group_sid%5Bequal%5D=&adv_button=" title="Rs. 2 - 4 Lakhs "><span class="WebRupee">Rs.</span> 2 - 4 Lakhs </a></li>
			<li><a href="http://classifieds.team-bhp.com/search_results/?action=search&listing_type%5Bequal%5D=Car&MakeModel%5Btree%5D%5B1%5D=&MakeModel%5Btree%5D%5B2%5D=0&multyModelMode=&Price%5Bnot_less%5D=400000&Price%5Bnot_more%5D=600000&ZipCode%5Bgeo%5D%5Bradius%5D=150&ZipCode%5Bgeo%5D%5Blocation%5D=&CarYear%5Bnot_less%5D=1940&CarYear%5Bnot_more%5D=2011&CarMileage%5Bnot_more%5D=&CarRegistrationState%5Bequal%5D=&CarFuelType%5Bequal%5D=&CarTransmission%5Bequal%5D=&CarExteriorColor%5Bequal%5D=&CarTaxPaid%5Bequal%5D=&user_group_sid%5Bequal%5D=&adv_button=" title="Rs. 4 - 6 Lakhs "><span class="WebRupee">Rs.</span> 4 - 6 Lakhs </a></li>
			<li><a href="http://classifieds.team-bhp.com/search_results/?action=search&listing_type%5Bequal%5D=Car&MakeModel%5Btree%5D%5B1%5D=&MakeModel%5Btree%5D%5B2%5D=0&multyModelMode=&Price%5Bnot_less%5D=600000&Price%5Bnot_more%5D=800000&ZipCode%5Bgeo%5D%5Bradius%5D=150&ZipCode%5Bgeo%5D%5Blocation%5D=&CarYear%5Bnot_less%5D=1940&CarYear%5Bnot_more%5D=2011&CarMileage%5Bnot_more%5D=&CarRegistrationState%5Bequal%5D=&CarFuelType%5Bequal%5D=&CarTransmission%5Bequal%5D=&CarExteriorColor%5Bequal%5D=&CarTaxPaid%5Bequal%5D=&user_group_sid%5Bequal%5D=&adv_button=" title="Rs. 6 - 8 Lakhs"><span class="WebRupee">Rs.</span> 6 - 8 Lakhs</a></li>
			<li class="last"><a href="http://classifieds.team-bhp.com/search_results/?action=search&listing_type%5Bequal%5D=Car&MakeModel%5Btree%5D%5B1%5D=&MakeModel%5Btree%5D%5B2%5D=0&multyModelMode=&Price%5Bnot_less%5D=800000&Price%5Bnot_more%5D=4000000&ZipCode%5Bgeo%5D%5Bradius%5D=150&ZipCode%5Bgeo%5D%5Blocation%5D=&CarYear%5Bnot_less%5D=1940&CarYear%5Bnot_more%5D=2011&CarMileage%5Bnot_more%5D=&CarRegistrationState%5Bequal%5D=&CarFuelType%5Bequal%5D=&CarTransmission%5Bequal%5D=&CarExteriorColor%5Bequal%5D=&CarTaxPaid%5Bequal%5D=&user_group_sid%5Bequal%5D=&adv_button=" title="Rs. 8 Lakhs or more"><span class="WebRupee">Rs.</span> 8 Lakhs or more</a></li>
		</ul>
</div><!-- Buy and Sell by City CTA -->
